; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Jul 18 2021 10:43:33 GMT+0200 (CEST)
; Wait for set temperatures to be reached
M116 P0

